# This is a basic workflow to help you get started with Actions

name: CI to Media Temple

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fast FTP
      uses: anvil-solutions/Fast-FTP-Action@2.1.3
      with:
        server: ${{ secrets.SERVER_IP }} 
        username: ${{ secrets.SERVER_USERNAME }} 
        password: ${{ secrets.FTP_PASSWORD }}
        method: sftp
        local_dir: './dist/'
        remote_dir: '/home/191393/domains/jordanairwave.co.uk/html/'
